[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "d7060f9b7d67337d73bf91769522300984cc72e1"
os = "macos"

    [[DuckDB.download]]
    sha256 = "1785bb9f7f0b26f583897f7c9e3ffaffd0b3b94a0038cdc3e5f41e3ead9488b8"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.aarch64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55de976c63272972fcc9d4f5501ada4eb76d3ff2"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "7265733e2b69a91ac84686c7884465964dad2f2847cd174a2012e66b814d855b"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.aarch64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f25c0ed7a84b397bbac8fc6b50ca984ea7e22cf9"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "555dd05753a8c3477420c07b60bbe81c01f8bbb9227f62894afe6187a15c49c3"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.aarch64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "d906cfc975d810949a33fc52b86280671910b76e"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "22c36b83f91592279a06154bd0abecca04dfbd126db73bcfff49f3d36053317a"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.aarch64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05755a9a013b0983b055d3b7641f7436a416dca0"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "53d4f87204b547814dfef7ba93188368a4bbe2c342789cc0923677c3c0e425de"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0fcd45b23e01d26f76a5b62086b34f58f058e7f"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "642862ff082648a21e6c37f16202821552cc251b05e3a35d766981b0d3c35297"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9816e38b9ccaea52d9768bb3ccf7a51e92659a03"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "f5cf2600d5c4f5e8c45355a44338f76fb0073ac53026dcca8f7658ebd65b54e3"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ed86bd796bcb842017b335860cee731a02facf9"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "585f714cf7bbc61b3e17951908df0f3c0c6c9e86035dbe79d94378ecb608ef05"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f9eda614ae0dba410f6887a0c17a5a23c7c8f9e"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "d4cc42746673377735c878f97b24b1b224a91276360dc75f90d810bdd398a51f"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.i686-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04e8d6b21f45d110d6734a7f214567dc113dda1f"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "d2e1d2ecdac47c68d8466c413530bd4fb8a43a3cfd99769ad0d95306356e1319"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.i686-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfac2f0960e05a8d933d88c7fc7ed1cb225ed834"
os = "windows"

    [[DuckDB.download]]
    sha256 = "50a7eab71bc0d06d44bc0d6a567fcd67d4673abd01cd9f68b58f05e683d9026f"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.i686-w64-mingw32-cxx11.tar.gz"
[[DuckDB]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cccd6ddf4297789fc0a93585d6b6188b126b8a1"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "cd95dc669a0152e391e9f6efb169ec09d85730bf027102a6106eda513c90961c"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.riscv64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "3f69ec5b76dd86f51409102249b6473392f508aa"
os = "macos"

    [[DuckDB.download]]
    sha256 = "ebb1cfc57e65d3c919112db55b43dab7fe8ac3ad1f867eca0cfe4e76a0994ccf"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.x86_64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46c6d1afda1af6e591be8a805a83cd2d6748cd3a"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "3752529bb0f1eefc024f3889df2f223d9510890262612c73e4988b0e558b765d"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.x86_64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a7166100295d5055b333f722dba2dfa7a8ec5d1"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "68cf6e28e1ba6ba3bb780edfcc98380442f569e88ff7d108ccd6102eab7a1ceb"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.x86_64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "0f0805b614ebeed36a54754a1587c274027e7423"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "de3a488764acf1fd23902b73d4476c24e6ee93dec56cc1295e2af57fef925f88"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.x86_64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "931cee18822bd4dc0b7e8f723a294fab4aa526c7"
os = "windows"

    [[DuckDB.download]]
    sha256 = "4a73ebc739a21d7ba77e5fc1ff8dd7f2163f3e9bcbd10c304622907317d2676a"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.4+0/DuckDB.v1.5.4.x86_64-w64-mingw32-cxx11.tar.gz"
