[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "e581e63e35218b70e7a87b61f9150afba28a7f08"
os = "macos"

    [[DuckDB.download]]
    sha256 = "9d490904ffc3d4bd164c1109fbad3a823dee05aa7e43047fcd03d1209a21a9ab"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.aarch64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f33bbea812bf49c90d6b1804ccc747d6d9b09af"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "dd8d2cf72d91799688f471daf54e6980a03adea4a6d38592669edbd28262ebdf"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.aarch64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cd713c7c2c2ebcacc461397a605a5c67958f28d"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "f86cdefb6b420c89c2c8fd3fa285c3f00085a36bae099a408ef6283a47594a7f"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.aarch64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "8d003ed3c105aab896fafa7030b47086e93191c0"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "3df183a2838f20f68c18c6be528c187b449dbd5bbb4dfbefc6d0293775937a75"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.aarch64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2094305f8d5f3ef8cae8192fa286b53cdb2b3a0"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "d95679fd1be8a94027cc1847ba86a8ac51b7ae2be2858cf6807dc479d127180d"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4042de5af07c4a72c1d275dc1f70ac20ce3fc05"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "c3fb324261e088938d84b38749b9275101656f64b8657a6bce5e0d34c10a8d0e"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f7a2c1848f1e683e8bcf5310963ec38e25eaad8"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "c07746013d2e3a9189f76143bc2cc3560ecb820bb65100cc5d2defd520da8b00"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2f7558ab46854d649040c01cfcf30f4dd2ca6b4"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "784916879f63f4cc249453e7268882bf7474785196e7c0846a4622dc34e1f9ae"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57850bbfab1fd6638b3189f39b7992ab7648b08c"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "6bcfb795dc404a095160a50ad510970ba48a6755c8c21e8470ee607f19f3c771"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.i686-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0c2a5a61040faf9a8daf0ab604415c1bf1c741e"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "61f5bfbacb8414d29bf25d1e34e5fd92e7821e685e9df848aaf8e3db8f76e183"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.i686-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07e33f3b995dacbf9c1a28043baede2d4398a255"
os = "windows"

    [[DuckDB.download]]
    sha256 = "d353e27be69a1bb7f3d3a698b27b5574bfdfd813214df5e172a957ef0609b2df"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.i686-w64-mingw32-cxx11.tar.gz"
[[DuckDB]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bff1da1337491df77ff7f0916e4069c473b8ffb9"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "6f8e3e5bf2f8c0fdac33a3e16261e38a4f30bfab96f639cbfe245eb3534d0f1a"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.riscv64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "c8ffa6347ed5b63f79972fad57e85c5fe4d8d8f3"
os = "macos"

    [[DuckDB.download]]
    sha256 = "ed6e4ce4e7ef78400aff90703fd08ae87d02b33d27f818acc145f45b44b11df8"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.x86_64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7971413e172a5cbc6c51def53e8675a44ec31150"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "879c8eb761dfb4c896f8e218ec5b9f0fdd4dc8e6e301ad13f0f2c12fe3f014f1"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3d673a65af107bb496f893f45df90c98346ba05"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "f712d6badbcff6538dcf887a7ad20b4e4bca517f4ab9e28b434a6b1c41b8340f"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.x86_64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "69138213c5fc69ace6becaf7b2bb0184b0283856"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "ee3604584bd90826f55e3e32b9bea1573733ebdf9b5290feea09e8643c841f16"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.x86_64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "100b72657a304e102f565d0f6f631a99525f44df"
os = "windows"

    [[DuckDB.download]]
    sha256 = "b4a5be6309535248b851f828b807b53bdb45eb0357e575801187d72491612741"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.1+0/DuckDB.v1.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
