[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "bdc3c4b850440fda10649e5d9562cc04d34faf3f"
os = "macos"

    [[DuckDB.download]]
    sha256 = "bc7b91f5a2cf03f5ca5644a5ef8a1941522aefb0368b7f1a4fdbe86f14f6f534"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.aarch64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1955a1b916d54f829ef2e2970d1e36f95e59e277"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "e2fea84311014d4bbc7fc668756ded093a15df1e56b8499e18614146913c54c9"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.aarch64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6acb2bbc9a622bd820f423d6249faa724e31bd8a"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "e7181fe0e0d39f31daa955e99b406b992d795b296a160e661d8ff8d87b73cdcd"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.aarch64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "c9ab46be16e8e3a4fdca9b05424260b28f3bb85b"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "424d13746392ccbe2f55bb38ea4ab05fd85e9aacdc56ae29f9fcd01a474c0fcb"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.aarch64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bb2f14559967aaec6c953881f74125510853a21"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "7ea38bf949cc878142e8191ad88d5b6bf7c499d18d92aebd3901841dc56b8426"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ff54b316fc020f9b553011ab5a53d655d9725a5"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "d31db7c99c1025937cd037c28ee6e03462661d59d73d08eff7bbf972329b0e7e"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "269671b43d257bf9436846e061dea92efbb27a7f"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "c40d4a40ab93216012b74a87416c61ce0b7ff387e8cacf19a45b6d6beed8c450"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0eb4e13d4eb12b09838b8421ddc24e8e20ff82c5"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "63bf067421ea8ac8257f50fdeb25048a01910ef3cd9906e0172a32370fb413ae"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84950f2ea0aab4eac8d04721ac8068664e27f3c5"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "9c7a32654155a5d253d2a14cab6edfe752334a7f2969b23aaf1bc82100db157d"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.i686-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a43453bd558a4e1bc4ff96a071240f17b8964737"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "eba0d9087f587776b1ff16cf11bd1a7e82ab315c0998a4bc55a09cbbd712c86d"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.i686-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff408d9f7696b573fa7aff360ffd55fbcdb024d6"
os = "windows"

    [[DuckDB.download]]
    sha256 = "e6cecea3c4aa921e101433e53f04d5bc5d0b2d0c7f03681a1df04d5598ed4e21"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.i686-w64-mingw32-cxx11.tar.gz"
[[DuckDB]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcece32d24bfd4681bc8c5173af38e4323ef624d"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "15a59205efeaf69d7289dbf44b320ce93cde2fc99ec24e62a193a9d150c027f6"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.riscv64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "d0ea74760c9f0c9a2e05795c43a0a32f7226e119"
os = "macos"

    [[DuckDB.download]]
    sha256 = "b3c6b8015b090bf2f0cf03f64a618fd660bc1db22209fc05239cf6227d47bfed"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.x86_64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "383c2f1f2a0a3466bf7e881dbdeee6c10775d192"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "24cf0c9ff539c7905b2e659305e6860dd5690796c69930a578d55f0568037796"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.x86_64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edd9bef7932d91184d33417ccbff9e6f0ea0ae1f"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "fbf38088db9b7c1054b45c76674677e4fe1c80a20a7c62da88c6b05132d3be92"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.x86_64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "889f6554a16d281b1fbe13618299839181316e5b"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "e59f33e5554030820edd84766424cf4fddb2eefb88d1ffbf8ce738c8f78afee4"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.x86_64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58ffbe1b947cd2385e75718e248b9456020b85c3"
os = "windows"

    [[DuckDB.download]]
    sha256 = "39901ba83bbbdff726724fdb1eec69541d6264a337d005bdf9a52a2cc50c61ee"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.5.3+0/DuckDB.v1.5.3.x86_64-w64-mingw32-cxx11.tar.gz"
